====== Execution Results for Generated Solvers ======

--- Running: 1D_Diffusion.py ---
Exit Code: 0
Output:

Errors:

--------------------------------------------------

--- Running: 2D_Nonlinear_Convection.py ---
Exit Code: 0
Output:

Errors:
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Nonlinear_Convection.py:38: RuntimeWarning: overflow encountered in multiply
  u[1:-1, 1:-1] = un[1:-1, 1:-1] - dt*(un[1:-1, 1:-1]*(un[1:-1, 1:-1] - un[:-2, 1:-1])/dx + vn[1:-1, 1:-1]*(un[1:-1, 1:-1] - un[1:-1, :-2])/dy) + dt*f(X[1:-1, 1:-1], Y[1:-1, 1:-1], n*dt)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Nonlinear_Convection.py:38: RuntimeWarning: overflow encountered in divide
  u[1:-1, 1:-1] = un[1:-1, 1:-1] - dt*(un[1:-1, 1:-1]*(un[1:-1, 1:-1] - un[:-2, 1:-1])/dx + vn[1:-1, 1:-1]*(un[1:-1, 1:-1] - un[1:-1, :-2])/dy) + dt*f(X[1:-1, 1:-1], Y[1:-1, 1:-1], n*dt)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Nonlinear_Convection.py:38: RuntimeWarning: invalid value encountered in add
  u[1:-1, 1:-1] = un[1:-1, 1:-1] - dt*(un[1:-1, 1:-1]*(un[1:-1, 1:-1] - un[:-2, 1:-1])/dx + vn[1:-1, 1:-1]*(un[1:-1, 1:-1] - un[1:-1, :-2])/dy) + dt*f(X[1:-1, 1:-1], Y[1:-1, 1:-1], n*dt)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Nonlinear_Convection.py:39: RuntimeWarning: overflow encountered in multiply
  v[1:-1, 1:-1] = vn[1:-1, 1:-1] - dt*(un[1:-1, 1:-1]*(vn[1:-1, 1:-1] - vn[:-2, 1:-1])/dx + vn[1:-1, 1:-1]*(vn[1:-1, 1:-1] - vn[1:-1, :-2])/dy) + dt*f_v(X[1:-1, 1:-1], Y[1:-1, 1:-1], n*dt)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Nonlinear_Convection.py:39: RuntimeWarning: overflow encountered in divide
  v[1:-1, 1:-1] = vn[1:-1, 1:-1] - dt*(un[1:-1, 1:-1]*(vn[1:-1, 1:-1] - vn[:-2, 1:-1])/dx + vn[1:-1, 1:-1]*(vn[1:-1, 1:-1] - vn[1:-1, :-2])/dy) + dt*f_v(X[1:-1, 1:-1], Y[1:-1, 1:-1], n*dt)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Nonlinear_Convection.py:39: RuntimeWarning: invalid value encountered in add
  v[1:-1, 1:-1] = vn[1:-1, 1:-1] - dt*(un[1:-1, 1:-1]*(vn[1:-1, 1:-1] - vn[:-2, 1:-1])/dx + vn[1:-1, 1:-1]*(vn[1:-1, 1:-1] - vn[1:-1, :-2])/dy) + dt*f_v(X[1:-1, 1:-1], Y[1:-1, 1:-1], n*dt)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Nonlinear_Convection.py:38: RuntimeWarning: invalid value encountered in subtract
  u[1:-1, 1:-1] = un[1:-1, 1:-1] - dt*(un[1:-1, 1:-1]*(un[1:-1, 1:-1] - un[:-2, 1:-1])/dx + vn[1:-1, 1:-1]*(un[1:-1, 1:-1] - un[1:-1, :-2])/dy) + dt*f(X[1:-1, 1:-1], Y[1:-1, 1:-1], n*dt)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Nonlinear_Convection.py:39: RuntimeWarning: invalid value encountered in subtract
  v[1:-1, 1:-1] = vn[1:-1, 1:-1] - dt*(un[1:-1, 1:-1]*(vn[1:-1, 1:-1] - vn[:-2, 1:-1])/dx + vn[1:-1, 1:-1]*(vn[1:-1, 1:-1] - vn[1:-1, :-2])/dy) + dt*f_v(X[1:-1, 1:-1], Y[1:-1, 1:-1], n*dt)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Nonlinear_Convection.py:38: RuntimeWarning: overflow encountered in add
  u[1:-1, 1:-1] = un[1:-1, 1:-1] - dt*(un[1:-1, 1:-1]*(un[1:-1, 1:-1] - un[:-2, 1:-1])/dx + vn[1:-1, 1:-1]*(un[1:-1, 1:-1] - un[1:-1, :-2])/dy) + dt*f(X[1:-1, 1:-1], Y[1:-1, 1:-1], n*dt)

--------------------------------------------------

--- Running: 2D_Diffusion.py ---
Exit Code: 1
Output:

Errors:
Traceback (most recent call last):
  File "/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Diffusion.py", line 33, in <module>
    u[1:-1, 1:-1, n+1] = u[1:-1, 1:-1, n] + alpha*dt*(np.diff(u[:-2, 1:-1, n],2,axis=0)/dx**2 + np.diff(u[1:-1, :-2, n],2,axis=1)/dy**2) + dt*f(X[1:-1, 1:-1], Y[1:-1, 1:-1], t[n])
ValueError: operands could not be broadcast together with shapes (97,99) (99,97) 

--------------------------------------------------

--- Running: 1D_Linear_Convection.py ---
Exit Code: 1
Output:

Errors:
Traceback (most recent call last):
  File "/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/1D_Linear_Convection.py", line 75, in <module>
    plt.contourf(x, t, u_mms, cmap='viridis')
  File "/home/weichao/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2537, in contourf
    __ret = gca().contourf(
  File "/home/weichao/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1446, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/weichao/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 6465, in contourf
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "/home/weichao/.local/lib/python3.8/site-packages/matplotlib/contour.py", line 769, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "/home/weichao/.local/lib/python3.8/site-packages/matplotlib/contour.py", line 1411, in _process_args
    x, y, z = self._contour_args(args, kwargs)
  File "/home/weichao/.local/lib/python3.8/site-packages/matplotlib/contour.py", line 1450, in _contour_args
    x, y, z = self._check_xyz(x, y, z_orig, kwargs)
  File "/home/weichao/.local/lib/python3.8/site-packages/matplotlib/contour.py", line 1475, in _check_xyz
    raise TypeError(f"Input z must be 2D, not {z.ndim}D")
TypeError: Input z must be 2D, not 1D

--------------------------------------------------

--- Running: 2D_Wave_Equation.py ---
Exit Code: 0
Output:

Errors:

--------------------------------------------------

--- Running: 2D_Navier_Stokes.py ---
Exit Code: 0
Output:

Errors:
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:43: RuntimeWarning: overflow encountered in scalar power
  p[i,j,k+1] = p[i,j,k] + dt*(-rho*(du_dx**2 + 2*du_dy*dv_dx + dv_dy**2))
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:43: RuntimeWarning: overflow encountered in scalar multiply
  p[i,j,k+1] = p[i,j,k] + dt*(-rho*(du_dx**2 + 2*du_dy*dv_dx + dv_dy**2))
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:41: RuntimeWarning: overflow encountered in scalar multiply
  u[i,j,k+1] = u[i,j,k] + dt*(-u[i,j,k]*du_dx - v[i,j,k]*du_dy + nu*(d2u_dx2 + d2u_dy2) - dp_dx/rho)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:42: RuntimeWarning: overflow encountered in scalar multiply
  v[i,j,k+1] = v[i,j,k] + dt*(-u[i,j,k]*dv_dx - v[i,j,k]*dv_dy + nu*(d2v_dx2 + d2v_dy2) - dp_dy/rho)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:43: RuntimeWarning: invalid value encountered in scalar add
  p[i,j,k+1] = p[i,j,k] + dt*(-rho*(du_dx**2 + 2*du_dy*dv_dx + dv_dy**2))
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:41: RuntimeWarning: invalid value encountered in scalar subtract
  u[i,j,k+1] = u[i,j,k] + dt*(-u[i,j,k]*du_dx - v[i,j,k]*du_dy + nu*(d2u_dx2 + d2u_dy2) - dp_dx/rho)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:42: RuntimeWarning: invalid value encountered in scalar subtract
  v[i,j,k+1] = v[i,j,k] + dt*(-u[i,j,k]*dv_dx - v[i,j,k]*dv_dy + nu*(d2v_dx2 + d2v_dy2) - dp_dy/rho)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:34: RuntimeWarning: invalid value encountered in scalar subtract
  dp_dx = (p[i+1,j,k] - p[i-1,j,k]) / (2*dx)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:35: RuntimeWarning: invalid value encountered in scalar subtract
  dp_dy = (p[i,j+1,k] - p[i,j-1,k]) / (2*dy)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:30: RuntimeWarning: invalid value encountered in scalar subtract
  du_dx = (u[i+1,j,k] - u[i-1,j,k]) / (2*dx)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:31: RuntimeWarning: invalid value encountered in scalar subtract
  du_dy = (u[i,j+1,k] - u[i,j-1,k]) / (2*dy)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:32: RuntimeWarning: invalid value encountered in scalar subtract
  dv_dx = (v[i+1,j,k] - v[i-1,j,k]) / (2*dx)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:33: RuntimeWarning: invalid value encountered in scalar subtract
  dv_dy = (v[i,j+1,k] - v[i,j-1,k]) / (2*dy)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:41: RuntimeWarning: invalid value encountered in scalar add
  u[i,j,k+1] = u[i,j,k] + dt*(-u[i,j,k]*du_dx - v[i,j,k]*du_dy + nu*(d2u_dx2 + d2u_dy2) - dp_dx/rho)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:42: RuntimeWarning: invalid value encountered in scalar add
  v[i,j,k+1] = v[i,j,k] + dt*(-u[i,j,k]*dv_dx - v[i,j,k]*dv_dy + nu*(d2v_dx2 + d2v_dy2) - dp_dy/rho)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:36: RuntimeWarning: invalid value encountered in scalar subtract
  d2u_dx2 = (u[i+1,j,k] - 2*u[i,j,k] + u[i-1,j,k]) / (dx**2)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:38: RuntimeWarning: invalid value encountered in scalar subtract
  d2v_dx2 = (v[i+1,j,k] - 2*v[i,j,k] + v[i-1,j,k]) / (dx**2)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:37: RuntimeWarning: invalid value encountered in scalar subtract
  d2u_dy2 = (u[i,j+1,k] - 2*u[i,j,k] + u[i,j-1,k]) / (dy**2)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:39: RuntimeWarning: invalid value encountered in scalar subtract
  d2v_dy2 = (v[i,j+1,k] - 2*v[i,j,k] + v[i,j-1,k]) / (dy**2)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:36: RuntimeWarning: invalid value encountered in scalar add
  d2u_dx2 = (u[i+1,j,k] - 2*u[i,j,k] + u[i-1,j,k]) / (dx**2)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:37: RuntimeWarning: invalid value encountered in scalar add
  d2u_dy2 = (u[i,j+1,k] - 2*u[i,j,k] + u[i,j-1,k]) / (dy**2)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:38: RuntimeWarning: invalid value encountered in scalar add
  d2v_dx2 = (v[i+1,j,k] - 2*v[i,j,k] + v[i-1,j,k]) / (dx**2)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Navier_Stokes.py:39: RuntimeWarning: invalid value encountered in scalar add
  d2v_dy2 = (v[i,j+1,k] - 2*v[i,j,k] + v[i,j-1,k]) / (dy**2)

--------------------------------------------------

--- Running: 2D_Euler_Equations.py ---
Exit Code: 1
Output:

Errors:
Traceback (most recent call last):
  File "/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Euler_Equations.py", line 52, in <module>
    rho, u, v, E = solve()
  File "/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Euler_Equations.py", line 42, in solve
    rho, u, v, E = MMS(0)
  File "/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Euler_Equations.py", line 28, in MMS
    E = p/(gamma-1) + 0.5*rho*(u**2 + v**2)
NameError: name 'gamma' is not defined

--------------------------------------------------

--- Running: 1D_Korteweg_de_Vries.py ---
Exit Code: 0
Output:

Errors:

--------------------------------------------------

--- Running: 1D_Nonlinear_Convection.py ---
Exit Code: 0
Output:

Errors:
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/1D_Nonlinear_Convection.py:41: RuntimeWarning: overflow encountered in scalar multiply
  u[n+1, i] = u[n, i] - dt/dx * u[n, i] * (u[n, i] - u[n, i-1]) + dt * f(x[i], t[n])
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/1D_Nonlinear_Convection.py:41: RuntimeWarning: invalid value encountered in scalar subtract
  u[n+1, i] = u[n, i] - dt/dx * u[n, i] * (u[n, i] - u[n, i-1]) + dt * f(x[i], t[n])

--------------------------------------------------

--- Running: 2D_Linear_Convection.py ---
Exit Code: 0
Output:

Errors:

--------------------------------------------------

--- Running: 1D_Wave_Equation.py ---
Exit Code: 0
Output:

Errors:

--------------------------------------------------

--- Running: 1D_Burgers_Equation.py ---
Exit Code: 0
Output:

Errors:
/home/weichao/.local/lib/python3.8/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py:214: SparseEfficiencyWarning: spsolve requires A be CSC or CSR matrix format
  warn('spsolve requires A be CSC or CSR matrix format',

--------------------------------------------------

--- Running: 1D_Kuramoto_Sivashinsky.py ---
Exit Code: 1
Output:

Errors:
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/1D_Kuramoto_Sivashinsky.py:46: RuntimeWarning: overflow encountered in square
  u[n + 1, :] = u[n, :] + dt * (u_xx + u_xxxx + 0.5 * u_x**2 + F)
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/1D_Kuramoto_Sivashinsky.py:40: RuntimeWarning: invalid value encountered in multiply
  u_xx = ifft(-k**2 * u_hat).real
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/1D_Kuramoto_Sivashinsky.py:41: RuntimeWarning: invalid value encountered in multiply
  u_xxxx = ifft(k**4 * u_hat).real
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/1D_Kuramoto_Sivashinsky.py:42: RuntimeWarning: invalid value encountered in multiply
  u_x = ifft(1j * k * u_hat).real
/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/1D_Kuramoto_Sivashinsky.py:43: RuntimeWarning: invalid value encountered in multiply
  u_xx = ifft(-k**2 * u_hat).real
Traceback (most recent call last):
  File "/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/1D_Kuramoto_Sivashinsky.py", line 52, in <module>
    error = np.abs(u - u_exact_sol)
ValueError: operands could not be broadcast together with shapes (1000,100) (100,1000) 

--------------------------------------------------

--- Running: 1D_Euler_Equations.py ---
Exit Code: 1
Output:

Errors:
Traceback (most recent call last):
  File "/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/1D_Euler_Equations.py", line 47, in <module>
    U = odeint(dUdt, U0, x)
  File "/home/weichao/.local/lib/python3.8/site-packages/scipy/integrate/_odepack_py.py", line 242, in odeint
    output = _odepack.odeint(func, y0, t, args, Dfun, col_deriv, ml, mu,
ValueError: Initial condition y0 must be one-dimensional.

--------------------------------------------------

--- Running: 2D_Burgers_Equation.py ---
Exit Code: 1
Output:

Errors:
Traceback (most recent call last):
  File "/opt/CFD-Benchmark/PDE_Benchmark/solver/generated_solvers/2D_Burgers_Equation.py", line 40, in <module>
    u_x = fftpack.diff(u, period=1.0, axis=1)
TypeError: diff() got an unexpected keyword argument 'axis'

--------------------------------------------------

